# Generated by Django 6.0.6 on 2026-07-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_subtitle'),
        ('blog', '0004_blog_subtitle'),
    ]

    operations = [
    ]
