# Generated by Django 5.1.5 on 2025-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addr',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
