# Generated by Django 6.0.6 on 2026-07-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_addres'),
        ('orders', '0004_address_addr'),
    ]

    operations = [
    ]
