# Generated by Django 6.0.6 on 2026-07-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_0003_addres_0004_address_addr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.DeleteModel(
            name='Addres',
        ),
    ]
