# Generated by Django 6.0.6 on 2026-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orderitem_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
            preserve_default=False,
        ),
    ]
