# Generated by Django 6.0.6 on 2026-07-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_orderitem_transaction'),
        ('orders', '0010_remove_order_amount'),
    ]

    operations = [
    ]
