# Generated by Django 6.0.6 on 2026-07-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20260703_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
    ]
