# Generated by Django 6.0.6 on 2026-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_orderitem_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='authority',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(default='ZarinPal', max_length=50, verbose_name='درگاه پرداخت'),
        ),
    ]
