# Generated by Django 6.0.6 on 2026-07-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_transaction_options_transaction_authority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_hash',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_pan',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
