# Generated by Django 6.0.6 on 2026-07-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_created_at_and_more'),
        ('products', '0002_alter_product_options_product_content_and_more'),
    ]

    operations = [
    ]
