# Generated by Django 6.0.6 on 2026-07-03 10:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20260702_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='توضیحات'),
        ),
    ]
